[package]
name = "audio-metadata"
version = "0.1.0"
edition = "2024"
authors = ["Paul Schweigert <paul@paulschweigert.com>"]
description = "A command-line tool for managing audio file metadata"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
anyhow = "1.0"
regex = "1.10"
